name: Labeler_Manual
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  label:
    runs-on: ubuntu-latest
    needs : build
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name : resources
      run: ls -lart
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
